[theme]

# Primary accent color for interactive elements

#primaryColor = "#d33682"
primaryColor = "#0068c9"

# Background color for the main content area

backgroundColor = "#002b36"
#backgroundColor = "#262730"

# Background color used for the sidebar and most interactive widgets

#secondaryBackgroundColor = "#586e75"
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text

textColor = "#fff"
#textColor = "#262730"